### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by GrbavaCigla** [dmilos/color#4]
Hi, I need CMake support for my project. I saw pull request but it isn't in master branch.

**Comment by dmilos** [comment]
CMake in this project is just used for testing.
This library is headers only. There is no need to compile or perform some special preparation.

For CMake all you need is to add $\color\src to include path.

Example:
 Root folder of _color_ project is `c:\work\projects\color`.
 In CMakeLists.txt add line like this: 
   `target_include_directories(MyProjectName PUBLIC c:\work\projects\color\src )`

More details about that: https://stackoverflow.com/questions/13703647/how-to-properly-add-include-directories-with-cmake

**Comment by GrbavaCigla** [comment]
Yes, i found solution, forgot to close the issue, thanks!
